spring:
  application:
    name: mybatis-starter

  datasource:
    url: jdbc:mysql://localhost:3306/reggie?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  # 配置mapper.xml文件位置
  mapper-locations: classpath:mapper/UserMapper.xml