spring:
  application:
    name: spring-cloud-sentinel
  cloud:
    nacos:
      # nacos 注册中心地址
      discovery:
        server-addr: 127.0.0.1:8848
      # nacos 配置中心地址
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: localhost:8080   # 指定 Sentinel Dashboard 地址
        port: 8719                  # 客户端监控端口，用于与 Sentinel Dashboard 通信
      eager: true
      filter:
        enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        loggerLevel: HEADERS
        readTimeout: 5000
  httpclient:
    enabled: false
  okhttp:
    enabled: true

Server:
  port: 9000