spring:
  application:
    name: provider-service
  cloud:
    nacos:
      # nacos 注册中心
      discovery:
        server-addr: 127.0.0.1:8848   # nacos 注册中心地址
        namespace: public
      # nacos 配置中心
      config:
        import-check:
          enabled: false
server:
  port: 9000