# ShardingSphere 数据源配置
dataSources:
  ds0:   # 逻辑数据源名称
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo_ds0?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
  ds1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/demo_ds1?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

# ShardingSphere 规则配置，包含：数据分片、数据加密、读写分离等
rules:
  - !SHARDING
    tables:
      t_user:   # 逻辑表名
        # 真实存在数据库的物理表集合
        actualDataNodes: ds_$->{0..1}.t_user_$->{0..1}
        # 分库策略，缺省表示使用默认分库策略
        databaseStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: user-database-inline
        # 分表策略
        tableStrategy:
          standard:                                    # 用于单分片键的标准分片场景
            shardingColumn: user_id                    # 自定义分片字段
            shardingAlgorithmName: user-table-inline  # 自定义分片算法名称

    # 数据分片算法定义
    shardingAlgorithms:
      user-table-inline: # 表分片算法
        type: INLINE
        props:
          # 使用 user_id 字段的值来决定物理表（例如：${user_id % 2}，即根据 user_id 值对 2 取余，分到 0 或 1）
          inlineExpression: t_user_$->{user_id % 2}
      user-database-inline: # 数据库分片算法
        type: INLINE
        props:
          # 使用 user_id 字段的值来决定分库（例如：${user_id % 2}，即根据 user_id 值对 2 取余，分到 ds0 或 ds1）
          inlineExpression: ds$->{user_id % 2}

# 配置数据源的默认数据库连接池参数
props:
  # 是否打印逻辑SQL和实SQL，开发测试环境建议开放，生产环境建议关闭
  sql-show: true
